# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: "Summarization-Testing"
# apiKey: ${OPENAI_API_KEY}
prompts:
  - "Summarize this story file:./articles/stellas.cosmic.adventure.txt"

providers: [ollama:chat:llama3:8b]
  
tests:
  - id: test_summarization_fail
    assert:
      - type: not-contains
        value: AI language model
      - type: contains-all
        value:
          - "Stella"
          - "Mars"
          - "Jupiter"
          - "Cosmo"
      - type: contains
        value: "fughettaboutit"