# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide
description: "Summarization-Testing"
# apiKey: ${OPENAI_API_KEY}
prompts: prompt.txt
providers: [ollama:chat:llama3:8b]
tests: tests*.yaml
